ALTER TABLE doctors
ADD COLUMN IF NOT EXISTS address_street VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_city VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_state VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_landmark VARCHAR(255),
ADD COLUMN IF NOT EXISTS address_pincode VARCHAR(50);
